MVC/Controllers/PReviewController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Net;


namespace MVC.Controllers
{
    public class PReviewController : Controller
    {
        // GET: Review
        [HttpGet]
        public ActionResult GetToDoList()
        {
            List<ToDo> TD = new List<ToDo>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:8040/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.GetAsync("ToDo/GetTaskList");
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back student object
                    var readTask = response.Content.ReadAsAsync<List<ToDo>>();
                    readTask.Wait();
                    TD = readTask.Result;


                }
            }
            return View(TD);
        }
        public ActionResult GetReviewList()
        {
            List<TaskReview> TR = new List<TaskReview>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44328/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


                var responseTask = client.GetAsync("Review/GetTaskReviewList");
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back student object
                    var readTask = response.Content.ReadAsAsync<List<TaskReview>>();
                    readTask.Wait();
                    TR = readTask.Result;


                }
            }
            return View(TR);
        }



        [HttpGet]
        public ActionResult GetTaskReviewbytheirID(int ToDoId)
        {
            List<TaskReview> TR = new List<TaskReview>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44328/api/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //HTTP GET - Get a student by the Student Id
                var responseTask = client.GetAsync("Review/GetTaskReviewbytheirID?ToDoId=" + ToDoId.ToString());
                // HTTP Get with id and name parameters
                //var responseTask = client.GetAsync(String.Format("getstudentByname/?id={0}&name={1}", StdId, StdName));
                responseTask.Wait();

                HttpResponseMessage response = responseTask.Result;
                if (response.IsSuccessStatusCode)
                {
                    // Get back a single student object
                    var readTask = response.Content.ReadAsAsync<List<TaskReview>>();
                    readTask.Wait();
                    TR = readTask.Result;
                }
            }
            return View(TR);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( TaskReview Tr)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44328/api/Review");

                    var response = await client.PostAsJsonAsync("Review/PostReview", Tr);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("GetToDoList");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error try after some time.");
                    }
                }
            }
            return View(Tr);
        }
        public async Task<ActionResult> Edit(int ReviewID)
        {
            if (ReviewID == 0)
            {
                return View();
            }
            TaskReview Tr = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44328/api/Review/");

                var result = await client.GetAsync("GetReviewById?ReviewID=" + ReviewID.ToString());

                if (result.IsSuccessStatusCode)
                {
                    Tr = await result.Content.ReadAsAsync<TaskReview>();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }
            if (Tr == null)
            {
                return View();
            }
            return View(Tr);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TaskReview Tr)
        {
            if (ModelState.IsValid)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44328/api/Review/");
                    var response = await client.PutAsJsonAsync("Put", Tr);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("GetReviewList");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Server error try after some time.");
                    }
                }
                return RedirectToAction("GetReviewList");
            }
            return View(Tr);
        }

        public async Task<ActionResult> Delete(string ReviewID)
        {
            if (ReviewID == null)
            {
                return View();
            }
            TaskReview Tr = null;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44328/api/Review/");

                var result = await client.GetAsync("GetReviewById?ReviewID=" + ReviewID);

                if (result.IsSuccessStatusCode)
                {
                    Tr = await result.Content.ReadAsAsync<TaskReview>();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
            }

            if (Tr == null)
            {
                return View();
            }
            return View(Tr);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string ReviewID)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44328/api/Review/");

                var response = await client.DeleteAsync("DeleteReview/?ReviewID="+ ReviewID);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetReviewList");
                }
                else
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
            }
            return View();
        }

        //public ActionResult Create()
        //{
        //    //// Call the GetGradeList method of the API
        //    //List<int> gl = GetGradeList();
        //    //// Make a SelectList of the Gradelist and store it in a ViewBag
        //    //ViewBag.grdList = new SelectList(gl);

        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Create(TaskReview TR)
        //{

        //    String res = "";
        //    if (ModelState.IsValid)
        //    {
        //        using (var client = new HttpClient())
        //        {
        //            client.BaseAddress = new Uri("https://localhost:44378/api/Review/");
        //            client.DefaultRequestHeaders.Clear();
        //            client.DefaultRequestHeaders.AcceptLanguage.Add(new StringWithQualityHeaderValue("nl-NL"));

        //            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //            //HTTP POST
        //            var responseTask = client.PostAsJsonAsync(("PostReview"), TR);

        //            responseTask.Wait();

        //            HttpResponseMessage response = responseTask.Result;
        //            if (response.IsSuccessStatusCode)
        //            {

        //                var readTask = response.Content.ReadAsStringAsync();
        //                readTask.Wait();
        //                res = readTask.Result;
        //            }


        //        }


        //        //If successfully Inserted the Student record
        //        if (Convert.ToInt32(res) > 0)

        //            return RedirectToAction("GetReviewList");
        //        else
        //            // Something went wrong in the adding the record.

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - consumingWebAPI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light " style="background-color:cornflowerblue">
            <div class="container">

                <a class="navbar-brand" style="font-weight:600 ;color:black" asp-area="" asp-controller="Home" asp-action="Index">Review N Evolve</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse ">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item" style="font-weight:600 ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item" style="font-weight:600 ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item" style="font-weight:600 ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PReview" asp-action="GetToDoList">Tasks</a>
                        </li>
                        <li class="nav-item" style="font-weight:600 ">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PReview" asp-action="GetReviewList">Reviews</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2022 - Review N Evolve - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>